const test = require('node:test');
const assert = require('node:assert/strict');
const smoke = require('../lib/smoke-window.js');
const NOW = Date.parse('2026-09-05T12:00:00Z');
function samples(values) { return values.map((value, i) => ({ time: new Date(NOW + i * 3600000).toISOString(), pm25_ug_m3: value })); }
test('AQI categories preserve official breakpoints', () => { assert.equal(smoke.aqiCategory(50).label, 'Good'); assert.equal(smoke.aqiCategory(51).label, 'Moderate'); assert.equal(smoke.aqiCategory(101).label, 'Unhealthy for Sensitive Groups'); assert.equal(smoke.aqiCategory(151).label, 'Unhealthy'); assert.equal(smoke.aqiCategory(201).label, 'Very Unhealthy'); assert.equal(smoke.aqiCategory(301).label, 'Hazardous'); });
test('reportingarea parser separates observations and forecasts', () => { const text = ['09/05/26|09/05/26|08:00|EDT|0|O|Y|Detroit|MI|42.3314|-83.0458|PM2.5|72|Moderate|No||Michigan EGLE','09/05/26|09/06/26||EDT|1|F|Y|Detroit|MI|42.3314|-83.0458|PM2.5|58|Moderate|No|Improving.|Michigan EGLE','09/05/26|09/05/26|08:00|EDT|0|O|Y|Detroit|MI|42.3314|-83.0458|OZONE|40|Good|No||Michigan EGLE'].join('\n'); const rows = smoke.parseReportingArea(text); const bundle = smoke.selectAirNowBundle(rows, 42.4, -83.1); assert.equal(bundle.observation.aqi, 72); assert.equal(bundle.observation.pollutant, 'PM2.5'); assert.equal(bundle.forecasts.length, 1); });
test('nearest reporting area wins', () => { const rows = smoke.parseReportingArea(['09/05/26|09/05/26|08:00|EDT|0|O|Y|Bay City|MI|43.5945|-83.8889|PM2.5|46|Good|No||Michigan EGLE','09/05/26|09/05/26|08:00|MDT|0|O|Y|Denver|CO|39.7392|-104.9903|PM2.5|120|Unhealthy for Sensitive Groups|No||Colorado DPHE'].join('\n')); assert.equal(smoke.selectNearestAirNow(rows, 43.6, -83.9, { pollutant:'PM2.5', dataType:'O' }).reporting_area, 'Bay City'); });
test('NOAA identify catalog values pair to valid times', () => { const payload = { properties: { Values: ['12.5', '8.2', '5.1'] }, catalogItems: { features: [{ attributes: { idp_validtime: NOW, idp_issueddate: NOW - 6*3600000, idp_fcst_hour: 6 } },{ attributes: { idp_validtime: NOW+3600000, idp_issueddate: NOW-6*3600000, idp_fcst_hour: 7 } },{ attributes: { idp_validtime: NOW+2*3600000, idp_issueddate: NOW-6*3600000, idp_fcst_hour: 8 } }] } }; const rows = smoke.parseNoaaIdentify(payload, NOW); assert.equal(rows.length, 3); assert.equal(rows[1].pm25_ug_m3, 8.2); });
test('best window is lowest contiguous 3-hour modeled period', () => { const best = smoke.chooseBestWindow(samples([18,16,14,11,7,5,6,10]), 3, 24, NOW); assert.equal(best.start_time, '2026-09-05T16:00:00.000Z'); assert.equal(best.average_pm25_ug_m3, 6); });
test('best window rejects non-contiguous gaps', () => { const rows = samples([8,7,6,10,12]); rows[1].time = new Date(NOW+5*3600000).toISOString(); const best = smoke.chooseBestWindow(rows,3,24,NOW); assert.ok(best); assert.notEqual(best.start_time, rows[0].time); });
test('trend identifies improvement and worsening', () => { assert.equal(smoke.trendFromSamples(samples([20,20,19,19,18,18,10,9,9,8,8,8]),NOW).code,'improving'); assert.equal(smoke.trendFromSamples(samples([5,5,6,6,6,7,12,13,13,14,15,15]),NOW).code,'worsening'); });
test('confidence degrades rather than failing with one family missing', () => { const obs={aqi:64}; assert.equal(smoke.confidence({observation:obs,samples:samples(Array(20).fill(8))}).code,'high'); assert.equal(smoke.confidence({observation:null,samples:samples(Array(20).fill(8))}).code,'moderate'); assert.equal(smoke.confidence({observation:obs,samples:[]}).code,'low'); });
test('decision never calls modeled concentration an AQI forecast', () => { const best=smoke.chooseBestWindow(samples([15,12,8,6,5,5]),3,24,NOW); const result=smoke.decision({observation:{aqi:82},bestWindow:best,trend:{code:'improving',label:'Improving'}}); assert.match(result.explanation,/planning guidance, not an official AQI forecast/i); });
test('true no-evidence path remains explicit', () => { const conf=smoke.confidence({observation:null,samples:[]}); assert.equal(conf.code,'unavailable'); const result=smoke.decision({observation:null,bestWindow:null,trend:{code:'unknown',label:'Trend uncertain'},confidenceResult:conf}); assert.match(result.explanation,/too limited/i); });
test('FIRMS CSV parser limits detections by distance', () => { const api=require('../api/national-smoke-window.js')._test; const csv='latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight\n43.70,-84.00,330,0.4,0.4,2026-09-05,1200,N21,VIIRS,n,2.0NRT,300,8.4,D\n35,-100,330,0.4,0.4,2026-09-05,1200,N21,VIIRS,n,2.0NRT,300,5,D'; const rows=api.parseFirmsCsv(csv,43.6,-83.9); assert.equal(rows.length,1); assert.equal(rows[0].satellite,'N21'); });
